[0m19:03:19.758924 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002E4A982D0A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002E4A982ECC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002E4A982D100>]}


============================== 19:03:19.763410 | 068a2068-8a0b-4ff2-a764-a119ab50ad8d ==============================
[0m19:03:19.763410 [info ] [MainThread]: Running with dbt=1.9.3
[0m19:03:19.768573 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\mmustafov\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt init dbtlearn', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m19:03:19.789391 [debug] [MainThread]: Starter project path: C:\Users\mmustafov\my\dbt_airbnb\venv\Lib\site-packages\dbt\include\starter_project
[0m19:03:19.826376 [info ] [MainThread]: 
Your new dbt project "dbtlearn" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m19:03:19.829449 [info ] [MainThread]: Setting up your profile.
[0m19:03:26.646893 [debug] [MainThread]: Command `dbt init` succeeded at 19:03:26.646893 after 7.06 seconds
[0m19:03:26.646893 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002E4A892E9F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002E4A960F950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002E4A936D8B0>]}
[0m19:03:26.646893 [debug] [MainThread]: Flushing usage events
[0m19:03:27.314819 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m10:49:44.653509 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027C44CC8440>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027C46D3B260>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027C46D3A300>]}


============================== 10:49:44.667272 | 93bd72e8-83ef-463c-9872-9ce70609d0f7 ==============================
[0m10:49:44.667272 [info ] [MainThread]: Running with dbt=1.9.3
[0m10:49:44.668273 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\mmustafov\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt run', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m10:49:44.669271 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\mmustafov\my\dbt_airbnb\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:49:44.671274 [debug] [MainThread]: Command `dbt run` failed at 10:49:44.671274 after 0.23 seconds
[0m10:49:44.671274 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027C47172C00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027C477BD0D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027C4750B3B0>]}
[0m10:49:44.672274 [debug] [MainThread]: Flushing usage events
[0m10:49:45.326778 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m10:30:56.091877 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000176BAA59CD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000176BB45A1E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000176BB3633B0>]}


============================== 10:30:56.100876 | b68fd639-813d-47f9-a862-2ecf8391b4b7 ==============================
[0m10:30:56.100876 [info ] [MainThread]: Running with dbt=1.9.3
[0m10:30:56.101877 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\mmustafov\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt test --select dim_listings_cleansed', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m10:30:56.101877 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\mmustafov\my\dbt_airbnb\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:30:56.102876 [debug] [MainThread]: Command `dbt test` failed at 10:30:56.102876 after 0.21 seconds
[0m10:30:56.103876 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000176BB10E180>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000176BB45A1E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000176BAA59CD0>]}
[0m10:30:56.103876 [debug] [MainThread]: Flushing usage events
[0m10:30:56.880365 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:27:12.226508 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CD4FED8BF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CD4CD07620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CD5011A1E0>]}


============================== 11:27:12.232524 | dd424884-fe8f-4f7f-8072-e8df618e8248 ==============================
[0m11:27:12.232524 [info ] [MainThread]: Running with dbt=1.9.3
[0m11:27:12.233542 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\mmustafov\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt deps', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:27:12.234586 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\mmustafov\my\dbt_airbnb\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:27:12.235599 [debug] [MainThread]: Command `dbt deps` failed at 11:27:12.235599 after 0.18 seconds
[0m11:27:12.236594 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CD507780E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CD5011A1E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CD50335370>]}
[0m11:27:12.236594 [debug] [MainThread]: Flushing usage events
[0m11:27:12.969347 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:38:35.547051 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002DC462AF6E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002DC46BEE060>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002DC49C0A390>]}


============================== 12:38:35.555004 | 202b4682-8a6d-4b6f-9dab-45c7784fd87a ==============================
[0m12:38:35.555004 [info ] [MainThread]: Running with dbt=1.9.3
[0m12:38:35.556212 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\mmustafov\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt docs generate', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:38:35.556212 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\mmustafov\my\dbt_airbnb\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:38:35.557945 [debug] [MainThread]: Command `dbt docs generate` failed at 12:38:35.557945 after 0.28 seconds
[0m12:38:35.558956 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002DC4999DF40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002DC49C09850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002DC49C097C0>]}
[0m12:38:35.558956 [debug] [MainThread]: Flushing usage events
[0m12:38:36.308186 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:54:47.084428 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018C62E08E60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018C653B9BE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018C62D0E120>]}


============================== 17:54:47.094122 | a3ac9155-68fa-494b-9f59-6974a5d757c9 ==============================
[0m17:54:47.094122 [info ] [MainThread]: Running with dbt=1.9.3
[0m17:54:47.100674 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\mmustafov\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt ', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m17:54:47.100674 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path c:\Users\mmustafov\my\dbt_airbnb\dbtlearn\dbt_packages\dbt-utils-1.3.0\integration_tests\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:54:47.100674 [debug] [MainThread]: Command `cli deps` failed at 17:54:47.100674 after 0.63 seconds
[0m17:54:47.100674 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018C62E08E60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018C65365700>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018C65E16720>]}
[0m17:54:47.100674 [debug] [MainThread]: Flushing usage events
[0m17:54:47.711094 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:54:49.970203 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BBB0061400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BBAF93ED50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BBAD8D0770>]}


============================== 17:54:49.980322 | f4c3e6d1-1b9c-43da-9e52-a6f55636b7af ==============================
[0m17:54:49.980322 [info ] [MainThread]: Running with dbt=1.9.3
[0m17:54:49.980322 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\mmustafov\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt ', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m17:54:49.980322 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path c:\Users\mmustafov\my\dbt_airbnb\dbtlearn\dbt_packages\dbt-utils-1.3.0\integration_tests\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:54:49.983784 [debug] [MainThread]: Command `cli deps` failed at 17:54:49.983784 after 0.27 seconds
[0m17:54:49.985223 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BBB0532360>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BBB0062E10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BBB0586720>]}
[0m17:54:49.985223 [debug] [MainThread]: Flushing usage events
[0m17:54:50.599953 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:07:56.280600 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000292A98FA1E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000292A91D03B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000292A95195B0>]}


============================== 18:07:56.286613 | 1d7fff58-4134-4538-a6cf-93f0ec660dc1 ==============================
[0m18:07:56.286613 [info ] [MainThread]: Running with dbt=1.9.3
[0m18:07:56.287613 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\mmustafov\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt ', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m18:07:56.287613 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path c:\Users\mmustafov\my\dbt_airbnb\dbtlearn\dbt_packages\dbt-utils-1.3.0\integration_tests\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m18:07:56.289602 [debug] [MainThread]: Command `cli deps` failed at 18:07:56.289602 after 0.22 seconds
[0m18:07:56.289602 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000292A992FFB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000292A95E44A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000292A9A461E0>]}
[0m18:07:56.290599 [debug] [MainThread]: Flushing usage events
[0m18:07:56.922735 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:20:30.524956 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F8A7753F20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F8A41A6F90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F8A4A2E450>]}


============================== 18:20:30.532954 | 62ec150e-1f0f-49c3-a8ca-04c57e6fb76b ==============================
[0m18:20:30.532954 [info ] [MainThread]: Running with dbt=1.9.3
[0m18:20:30.533954 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\mmustafov\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt ', 'send_anonymous_usage_stats': 'True'}
[0m18:20:30.534958 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path c:\Users\mmustafov\my\dbt_airbnb\dbtlearn\dbt_packages\dbt-utils-1.3.0\integration_tests\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m18:20:30.536325 [debug] [MainThread]: Command `cli deps` failed at 18:20:30.536325 after 0.31 seconds
[0m18:20:30.537338 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F8A67D9280>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F8A7996F00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F8A54A0920>]}
[0m18:20:30.538336 [debug] [MainThread]: Flushing usage events
[0m18:20:31.131141 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:20:33.480137 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B6C2E8D520>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B6C2E8FEF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B6C2E8D340>]}


============================== 18:20:33.486616 | 433467fc-61c0-45af-96e6-59f31cd2e6e3 ==============================
[0m18:20:33.486616 [info ] [MainThread]: Running with dbt=1.9.3
[0m18:20:33.487619 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\mmustafov\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt ', 'send_anonymous_usage_stats': 'True'}
[0m18:20:33.487619 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path c:\Users\mmustafov\my\dbt_airbnb\dbtlearn\dbt_packages\dbt-utils-1.3.0\integration_tests\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m18:20:33.490141 [debug] [MainThread]: Command `cli deps` failed at 18:20:33.489127 after 0.22 seconds
[0m18:20:33.490141 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B6C3516CC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B6C12BA030>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B6C39720F0>]}
[0m18:20:33.491139 [debug] [MainThread]: Flushing usage events
[0m18:20:34.115688 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:25:52.485790 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000142424D03B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000142424F9580>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014242115220>]}


============================== 18:25:52.493788 | 9e42dbc9-e690-4877-ab4e-36c605e109c0 ==============================
[0m18:25:52.493788 [info ] [MainThread]: Running with dbt=1.9.3
[0m18:25:52.494788 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\mmustafov\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt ', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m18:25:52.495793 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path c:\Users\mmustafov\my\dbt_airbnb\dbtlearn\dbt_packages\dbt-utils-1.3.0\integration_tests\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m18:25:52.497790 [debug] [MainThread]: Command `cli deps` failed at 18:25:52.497790 after 0.32 seconds
[0m18:25:52.498791 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000142422E65A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014242A620F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014242984B30>]}
[0m18:25:52.498791 [debug] [MainThread]: Flushing usage events
[0m18:25:53.102169 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:25:55.281689 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021E1A4F68D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021E19D5ECC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021E19D5C8C0>]}


============================== 18:25:55.298166 | fe1dc166-602c-4549-98c0-bf6d9ddfa03a ==============================
[0m18:25:55.298166 [info ] [MainThread]: Running with dbt=1.9.3
[0m18:25:55.298166 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\mmustafov\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt ', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m18:25:55.298166 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path c:\Users\mmustafov\my\dbt_airbnb\dbtlearn\dbt_packages\dbt-utils-1.3.0\integration_tests\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m18:25:55.298166 [debug] [MainThread]: Command `cli deps` failed at 18:25:55.298166 after 0.26 seconds
[0m18:25:55.298166 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021E1A954F20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021E1789A660>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021E1A0E65A0>]}
[0m18:25:55.298166 [debug] [MainThread]: Flushing usage events
[0m18:25:56.022797 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m09:36:29.144370 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024B63ADE360>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024B66E73530>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024B66D4B3B0>]}


============================== 09:36:29.160979 | 2e99df07-ac5c-4820-a3f4-27e4565dc1c3 ==============================
[0m09:36:29.160979 [info ] [MainThread]: Running with dbt=1.9.3
[0m09:36:29.161967 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\mmustafov\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt ', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m09:36:29.162968 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path c:\Users\mmustafov\my\dbt_airbnb\dbtlearn\dbt_packages\dbt-utils-1.3.0\integration_tests\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:36:29.163968 [debug] [MainThread]: Command `cli deps` failed at 09:36:29.163968 after 0.24 seconds
[0m09:36:29.163968 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024B66F87410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024B67373A70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024B67373AD0>]}
[0m09:36:29.163968 [debug] [MainThread]: Flushing usage events
[0m09:36:29.650135 [debug] [MainThread]: An error was encountered while trying to flush usage events
